### ISSUE TITLE
builds please

### ISSUE THREAD

**Issue by Goten87** [jagannatharjun/qbt-theme#52]
the builds that are here are 5 months old can you please remake them in the git project

**Comment by GGODestroyer** [comment]
i think the project is dead

**Comment by DonaldsonTyler** [comment]
As far as I'm aware, the project is not dead. The project was updated just last month when a slight change was made and broke part of the the themes. 

You don't need an actual release or anything - all you need to do is download the master branch as a zip, unzip it, and use the qbtheme files in the root.

**Comment by yannduran** [comment]
@DonaldsonTyler 
>use the qbtheme files in the root.

Could you point me to somewhere that I can find out how to actually **_use_** any qbtheme files? Do they have to be compiled in with the code? Or is there a special place to put them? I'm using qBittorrent in a docker container, so that might make a difference as well.

I've been searching through any mention of 'theme' in the main qbittorrent repo. That's how I came across this one.

TIA

**Comment by jagannatharjun** [comment]
repo is always updated with the latest build. releases are old though.
